apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slipchuk-pvc
  namespace: slipchuk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
